### PR TITLE
Node.js example

### PR DESCRIPTION
**Pull request by synw**
A simple example with Node.js

### CODE REVIEW

**Comment by FZambia** [comment]
@synw thanks a lot! Will look very soon

**Comment by FZambia** [comment]
Could you add `package.json` file to help with installing dependencies?

**Comment by synw** [comment]
Ok I just need to figure out how to do it properly first. I am really not an npm fan, trying to avoid it as much as I can. That said I understand it can be useful for people here, so I'll give it a look when I can.

**Comment by FZambia** [comment]
From [this](http://stackoverflow.com/questions/17576243/pip-freeze-for-node-and-npm) SO answer:

```
npm ls | grep -E "^(├|└)─" | cut -d" " -f2 | awk -v quote='"' 'BEGIN { FS = "@" } ; { print quote $1 quote,":",quote $2 quote"," }' | sed -e 's/ :/:/g'
```

This line should show all dependencies like `pip freeze` for Python - if you prefer you can just run this command and paste output here - I'll add package.json myself

**Comment by synw** [comment]
Ok fine. Here is the output:
```
"ejs": "2.5.6",
"express": "4.15.2",
"jscent": "0.1.2",
"path": "0.12.7",
"sequelize": "3.30.4",
"sqlite3": "3.1.8",
```
I remember I just had to `npm install express path ejs jscent`: the other ones should be sub-dependencies I guess.

**Comment by FZambia** [comment]
thanks, will try to run on my machine and then merge

**Comment by FZambia** [comment]
@synw done, thanks again!

**Comment by synw** [comment]
No problem, if it helps that is good

**Pull request merged**
